/**
 * PDF Generator — B2B Procurement Documents
 *
 * Generates professional PDF documents for:
 *  - RFP (Request for Proposal) issued by a buyer company
 *  - Bid Response submitted by a vendor company
 *
 * Uses jsPDF (client-side, no server required).
 */

import { jsPDF } from "jspdf";

// ─── Colour palette ───────────────────────────────────────────────────────────
const NAVY   = [15,  40,  80]  as [number, number, number];
const BLUE   = [37,  99, 235]  as [number, number, number];
const SLATE  = [71,  85, 105]  as [number, number, number];
const LIGHT  = [241, 245, 249] as [number, number, number];
const WHITE  = [255, 255, 255] as [number, number, number];
const BLACK  = [15,  23,  42]  as [number, number, number];

// ─── Helpers ──────────────────────────────────────────────────────────────────

function header(doc: jsPDF, title: string, refNumber: string, date: string) {
  // Navy banner
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, 210, 32, "F");

  // Title
  doc.setTextColor(...WHITE);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(title, 14, 14);

  // Subtitle line
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Reference: ${refNumber}   |   Date: ${date}`, 14, 22);

  // Blue accent bar
  doc.setFillColor(...BLUE);
  doc.rect(0, 32, 210, 3, "F");
}

function sectionTitle(doc: jsPDF, text: string, y: number): number {
  doc.setFillColor(...LIGHT);
  doc.rect(14, y, 182, 8, "F");
  doc.setTextColor(...NAVY);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text(text.toUpperCase(), 17, y + 5.5);
  return y + 12;
}

function row(doc: jsPDF, label: string, value: string, y: number, shade: boolean): number {
  if (shade) {
    doc.setFillColor(248, 250, 252);
    doc.rect(14, y, 182, 7, "F");
  }
  doc.setTextColor(...SLATE);
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.text(label, 17, y + 5);
  doc.setTextColor(...BLACK);
  doc.setFont("helvetica", "bold");
  const lines = doc.splitTextToSize(value || "—", 120);
  doc.text(lines, 75, y + 5);
  return y + Math.max(7, lines.length * 5);
}

function bulletList(doc: jsPDF, items: string[], y: number): number {
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...BLACK);
  for (const item of items) {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.setFillColor(...BLUE);
    doc.circle(18, y + 3.5, 1, "F");
    const lines = doc.splitTextToSize(item, 170);
    doc.text(lines, 22, y + 5);
    y += Math.max(7, lines.length * 5);
  }
  return y;
}

function footer(doc: jsPDF, pageCount: number) {
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    doc.setFillColor(...LIGHT);
    doc.rect(0, 285, 210, 12, "F");
    doc.setTextColor(...SLATE);
    doc.setFontSize(7.5);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by Effix B2B CRM Platform — Confidential", 14, 292);
    doc.text(`Page ${i} of ${total}`, 196, 292, { align: "right" });
  }
}

// ─── RFP PDF ──────────────────────────────────────────────────────────────────

export interface RfpPdfData {
  refNumber: string;
  date: string;
  // Buyer company
  companyName: string;
  companyIce?: string;
  companyAddress?: string;
  companyEmail?: string;
  // RFP fields
  title: string;
  description: string;
  category: string;
  workflowType: string;
  budget: number | string;
  currency?: string;
  submissionDeadline: string;
  expectedDeliveryDate?: string;
  region?: string;
  evaluationCriteria?: string;
  conditions?: string;
  requirements?: string[];
  constraints?: string[];
  contactEmail?: string;
}

export function generateRfpPdf(data: RfpPdfData): Blob {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const ref = data.refNumber || `RFP-${Date.now()}`;
  const date = data.date || new Date().toLocaleDateString("fr-FR");

  header(doc, "REQUEST FOR PROPOSAL (RFP)", ref, date);

  let y = 42;

  // ── Issuing Company ──────────────────────────────────────────────────────
  y = sectionTitle(doc, "Issuing Company", y);
  y = row(doc, "Company Name",    data.companyName,              y, false);
  y = row(doc, "ICE / Tax ID",    data.companyIce  || "—",       y, true);
  y = row(doc, "Address",         data.companyAddress || "—",    y, false);
  y = row(doc, "Contact Email",   data.contactEmail || data.companyEmail || "—", y, true);
  y += 4;

  // ── RFP Details ──────────────────────────────────────────────────────────
  y = sectionTitle(doc, "RFP Details", y);
  y = row(doc, "RFP Title",           data.title,                                    y, false);
  y = row(doc, "Category",            data.category,                                 y, true);
  y = row(doc, "Contract Type",       data.workflowType,                             y, false);
  y = row(doc, "Budget Ceiling",      `${data.currency || "MAD"} ${Number(data.budget).toLocaleString()}`, y, true);
  y = row(doc, "Submission Deadline", data.submissionDeadline,                       y, false);
  y = row(doc, "Expected Delivery",   data.expectedDeliveryDate || "—",              y, true);
  y = row(doc, "Region / Scope",      data.region || "—",                            y, false);
  y += 4;

  // ── Description ──────────────────────────────────────────────────────────
  y = sectionTitle(doc, "Scope of Work & Description", y);
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...BLACK);
  const descLines = doc.splitTextToSize(data.description || "—", 178);
  if (y + descLines.length * 5 > 270) { doc.addPage(); y = 20; }
  doc.text(descLines, 17, y + 5);
  y += descLines.length * 5 + 8;

  // ── Requirements ─────────────────────────────────────────────────────────
  if (data.requirements && data.requirements.length > 0) {
    if (y > 240) { doc.addPage(); y = 20; }
    y = sectionTitle(doc, "Vendor Requirements", y);
    y = bulletList(doc, data.requirements, y);
    y += 4;
  }

  // ── Constraints ──────────────────────────────────────────────────────────
  if (data.constraints && data.constraints.length > 0) {
    if (y > 240) { doc.addPage(); y = 20; }
    y = sectionTitle(doc, "Constraints & Limitations", y);
    y = bulletList(doc, data.constraints, y);
    y += 4;
  }

  // ── Evaluation & Conditions ───────────────────────────────────────────────
  if (y > 240) { doc.addPage(); y = 20; }
  y = sectionTitle(doc, "Evaluation & Contract Conditions", y);
  y = row(doc, "Evaluation Criteria", data.evaluationCriteria || "—", y, false);
  y = row(doc, "Payment Conditions",  data.conditions || "—",         y, true);
  y += 4;

  // ── Submission Instructions ───────────────────────────────────────────────
  if (y > 240) { doc.addPage(); y = 20; }
  y = sectionTitle(doc, "Submission Instructions", y);
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...BLACK);
  const instructions = [
    `All bids must be submitted before ${data.submissionDeadline} via the Effix platform.`,
    "Bids must include a technical proposal and a financial quote.",
    "Incomplete submissions will be disqualified.",
    `For questions, contact: ${data.contactEmail || data.companyEmail || "—"}`,
  ];
  y = bulletList(doc, instructions, y);

  footer(doc, doc.getNumberOfPages());
  return doc.output("blob");
}

// ─── Bid PDF ──────────────────────────────────────────────────────────────────

export interface BidPdfData {
  refNumber: string;
  date: string;
  // Vendor company
  vendorName: string;
  vendorIce?: string;
  vendorAddress?: string;
  vendorEmail?: string;
  // Buyer / RFP context
  rfpTitle: string;
  rfpRef: string;
  buyerName?: string;
  // Bid fields
  proposedAmount: number | string;
  currency?: string;
  deliveryLeadTime: string;
  validUntil?: string;
  downPaymentPercentage?: number | string;
  balanceDueDays?: number | string;
  technicalApproach?: string;
  warranty?: string;
  vendorNotes?: string;
  complianceItems?: string[];
}

export function generateBidPdf(data: BidPdfData): Blob {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const ref = data.refNumber || `BID-${Date.now()}`;
  const date = data.date || new Date().toLocaleDateString("fr-FR");

  header(doc, "BID / VENDOR PROPOSAL", ref, date);

  let y = 42;

  // ── Vendor Company ───────────────────────────────────────────────────────
  y = sectionTitle(doc, "Submitting Vendor", y);
  y = row(doc, "Company Name",  data.vendorName,              y, false);
  y = row(doc, "ICE / Tax ID",  data.vendorIce  || "—",       y, true);
  y = row(doc, "Address",       data.vendorAddress || "—",    y, false);
  y = row(doc, "Contact Email", data.vendorEmail || "—",      y, true);
  y += 4;

  // ── RFP Reference ────────────────────────────────────────────────────────
  y = sectionTitle(doc, "RFP Reference", y);
  y = row(doc, "RFP Title",    data.rfpTitle,          y, false);
  y = row(doc, "RFP Number",   data.rfpRef,            y, true);
  y = row(doc, "Buyer Company", data.buyerName || "—", y, false);
  y += 4;

  // ── Financial Proposal ───────────────────────────────────────────────────
  y = sectionTitle(doc, "Financial Proposal", y);
  y = row(doc, "Proposed Amount",      `${data.currency || "MAD"} ${Number(data.proposedAmount).toLocaleString()}`, y, false);
  y = row(doc, "Down Payment",         data.downPaymentPercentage ? `${data.downPaymentPercentage}%` : "—",         y, true);
  y = row(doc, "Balance Due (days)",   data.balanceDueDays ? `${data.balanceDueDays} days` : "—",                   y, false);
  y = row(doc, "Bid Valid Until",      data.validUntil || "—",                                                       y, true);
  y += 4;

  // ── Delivery & Execution ─────────────────────────────────────────────────
  y = sectionTitle(doc, "Delivery & Execution", y);
  y = row(doc, "Delivery Lead Time", data.deliveryLeadTime || "—", y, false);
  y = row(doc, "Warranty / SLA",     data.warranty || "—",         y, true);
  y += 4;

  // ── Technical Approach ───────────────────────────────────────────────────
  if (data.technicalApproach) {
    if (y > 240) { doc.addPage(); y = 20; }
    y = sectionTitle(doc, "Technical Approach & Methodology", y);
    doc.setFontSize(8.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...BLACK);
    const lines = doc.splitTextToSize(data.technicalApproach, 178);
    doc.text(lines, 17, y + 5);
    y += lines.length * 5 + 8;
  }

  // ── Compliance ───────────────────────────────────────────────────────────
  if (data.complianceItems && data.complianceItems.length > 0) {
    if (y > 240) { doc.addPage(); y = 20; }
    y = sectionTitle(doc, "Compliance & Certifications", y);
    y = bulletList(doc, data.complianceItems, y);
    y += 4;
  }

  // ── Vendor Notes ─────────────────────────────────────────────────────────
  if (data.vendorNotes) {
    if (y > 240) { doc.addPage(); y = 20; }
    y = sectionTitle(doc, "Additional Notes", y);
    doc.setFontSize(8.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...BLACK);
    const lines = doc.splitTextToSize(data.vendorNotes, 178);
    doc.text(lines, 17, y + 5);
    y += lines.length * 5 + 8;
  }

  // ── Declaration ──────────────────────────────────────────────────────────
  if (y > 240) { doc.addPage(); y = 20; }
  y = sectionTitle(doc, "Vendor Declaration", y);
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...BLACK);
  const declaration = `${data.vendorName} hereby certifies that all information provided in this bid is accurate and complete. This proposal is valid until ${data.validUntil || "the submission deadline"} and constitutes a binding offer subject to contract negotiation.`;
  const declLines = doc.splitTextToSize(declaration, 178);
  doc.text(declLines, 17, y + 5);

  footer(doc, doc.getNumberOfPages());
  return doc.output("blob");
}

/** Convert a Blob to a data URL for <a download> */
export function blobToDataUrl(blob: Blob): Promise<string> {
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as string);
    reader.readAsDataURL(blob);
  });
}

/** Trigger a browser download of a Blob */
export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── BC (Bon de Commande / Purchase Order) PDF ────────────────────────────────

export interface BcPdfData {
  refNumber: string;
  date: string;
  buyerName: string;
  buyerIce?: string;
  buyerAddress?: string;
  vendorName: string;
  vendorIce?: string;
  vendorAddress?: string;
  rfpTitle: string;
  amount?: number | string;
  currency?: string;
  deliveryLeadTime?: string;
  downPaymentPercentage?: number | string;
  balanceDueDays?: number | string;
  conditions?: string;
  items?: { description: string; quantity: number; unitPrice: number; total: number }[];
  status?: "PENDING_VENDOR" | "SIGNED" | "REJECTED";
}

export function generateBcPdf(data: BcPdfData): Blob {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const ref = data.refNumber || `BC-${Date.now()}`;
  const date = data.date || new Date().toLocaleDateString("fr-FR");
  const statusLabel =
    data.status === "SIGNED" ? "SIGNED — CONTRACT ESTABLISHED" :
    data.status === "REJECTED" ? "REJECTED BY VENDOR" :
    "PENDING VENDOR ACCEPTANCE";

  // Header
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, 210, 32, "F");
  doc.setTextColor(...WHITE);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("BON DE COMMANDE (PURCHASE ORDER)", 14, 14);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Reference: ${ref}   |   Date: ${date}   |   Status: ${statusLabel}`, 14, 22);
  doc.setFillColor(...BLUE);
  doc.rect(0, 32, 210, 3, "F");

  let y = 42;

  // ── Parties ──────────────────────────────────────────────────────────────
  // Two-column party block
  doc.setFillColor(...LIGHT);
  doc.rect(14, y, 87, 30, "F");
  doc.rect(109, y, 87, 30, "F");

  doc.setTextColor(...NAVY);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text("BUYER (CLIENT)", 17, y + 6);
  doc.text("VENDOR (SELLER)", 112, y + 6);

  doc.setTextColor(...BLACK);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.text(data.buyerName, 17, y + 13);
  doc.text(`ICE: ${data.buyerIce || "—"}`, 17, y + 19);
  doc.text(data.buyerAddress || "—", 17, y + 25);

  doc.text(data.vendorName, 112, y + 13);
  doc.text(`ICE: ${data.vendorIce || "—"}`, 112, y + 19);
  doc.text(data.vendorAddress || "—", 112, y + 25);

  y += 36;

  // ── Order Details ─────────────────────────────────────────────────────────
  y = sectionTitle(doc, "Order Details", y);
  y = row(doc, "RFP / Project Title",   data.rfpTitle,                                                                    y, false);
  y = row(doc, "Total Amount",          `${data.currency || "MAD"} ${Number(data.amount || 0).toLocaleString()}`,         y, true);
  y = row(doc, "Delivery Lead Time",    data.deliveryLeadTime ? `${data.deliveryLeadTime} days` : "—",                    y, false);
  y = row(doc, "Down Payment",          data.downPaymentPercentage ? `${data.downPaymentPercentage}%` : "—",              y, true);
  y = row(doc, "Balance Due",           data.balanceDueDays ? `${data.balanceDueDays} days after delivery` : "—",        y, false);
  y = row(doc, "Payment Conditions",    data.conditions || "Standard Net 30",                                             y, true);
  y += 4;

  // ── Line Items (if provided) ──────────────────────────────────────────────
  if (data.items && data.items.length > 0) {
    y = sectionTitle(doc, "Line Items", y);
    // Table header
    doc.setFillColor(...NAVY);
    doc.rect(14, y, 182, 7, "F");
    doc.setTextColor(...WHITE);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text("Description", 17, y + 5);
    doc.text("Qty", 120, y + 5);
    doc.text("Unit Price", 140, y + 5);
    doc.text("Total", 170, y + 5);
    y += 7;

    data.items.forEach((item, i) => {
      if (y > 265) { doc.addPage(); y = 20; }
      if (i % 2 === 0) { doc.setFillColor(248, 250, 252); doc.rect(14, y, 182, 7, "F"); }
      doc.setTextColor(...BLACK);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      const descLines = doc.splitTextToSize(item.description, 95);
      doc.text(descLines, 17, y + 5);
      doc.text(String(item.quantity), 120, y + 5);
      doc.text(`${data.currency || "MAD"} ${item.unitPrice.toLocaleString()}`, 140, y + 5);
      doc.text(`${data.currency || "MAD"} ${item.total.toLocaleString()}`, 170, y + 5);
      y += 7;
    });

    // Total row
    doc.setFillColor(...NAVY);
    doc.rect(14, y, 182, 8, "F");
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text("TOTAL", 140, y + 5.5);
    doc.text(`${data.currency || "MAD"} ${Number(data.amount || 0).toLocaleString()}`, 170, y + 5.5);
    y += 12;
  }

  // ── Legal Terms ───────────────────────────────────────────────────────────
  if (y > 230) { doc.addPage(); y = 20; }
  y = sectionTitle(doc, "Legal Terms & Acceptance", y);
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...BLACK);
  const legalText = `This Purchase Order constitutes a binding offer from ${data.buyerName} to ${data.vendorName}. Upon vendor acceptance (signature or electronic confirmation), this document becomes a legally binding contract. The vendor must accept or reject this PO within 5 business days of receipt. Rejection must be accompanied by a written reason. Acceptance triggers the start of the contract execution phase.`;
  const legalLines = doc.splitTextToSize(legalText, 178);
  doc.text(legalLines, 17, y + 5);
  y += legalLines.length * 5 + 10;

  // ── Signature Block ───────────────────────────────────────────────────────
  if (y > 240) { doc.addPage(); y = 20; }
  doc.setFillColor(...LIGHT);
  doc.rect(14, y, 87, 28, "F");
  doc.rect(109, y, 87, 28, "F");

  doc.setTextColor(...NAVY);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text("BUYER SIGNATURE", 17, y + 6);
  doc.text("VENDOR SIGNATURE", 112, y + 6);

  doc.setTextColor(...SLATE);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(data.buyerName, 17, y + 14);
  doc.text("Date: _______________", 17, y + 22);
  doc.text(data.vendorName, 112, y + 14);
  doc.text(data.status === "SIGNED" ? `Date: ${date}` : "Date: _______________", 112, y + 22);

  footer(doc, doc.getNumberOfPages());
  return doc.output("blob");
}
